source:      .
destination: ./_site
plugins:     ./_plugins
exclude: [bin, CNAME, Gemfile, Gemfile.lock, README.md, Dockerfile, fig.yml]
permalink: /:title
highlighter: pygments
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
gems:
  - jekyll-sitemap
